[marketplace]
enabled = false
psk = "NebulaSecure2026"
level = 1

[seo]
enabled = false
domain = "https://nebulaproxy.io"

[db]
name = "railway"
username = "postgres"
password = ""
postgres = true # Unbedingt auf true, da wir Postgres nutzen!

[postgres] 
# Wir lassen domain leer, damit die App deine DATABASE_URL-Variable nutzt
domain = "" 
port = 5432

[server.server]
port = 8080
wisp = true
logging = true

[masqr]
enabled = false
failed = "failed.html"
whitelisted = ["https://nebulaservices.org"]
url = ""
