[marketplace]
enabled = false
psk = "NebulaSecure2026"
level = 1

[seo]
enabled = false
domain = "https://nebulaproxy.io"

[db]
name = "main"
username = "root"
password = ""
postgres = true # HIERMIT aktivieren wir die externe Datenbank!

[postgres] 
# Railway füllt diese Verbindung im Hintergrund über deine Variablen aus
domain = "${{MongoDB.MONGODB_URL}}" 
port = 27017

[server.server]
port = 8080
wisp = true
logging = true

[masqr]
enabled = false
failed = "failed.html"
whitelisted = ["https://nebulaservices.org"]
url = ""
